version: '3.5'

services:
  dev:
    container_name: tmpagent
    image: liyaodev/tmpagent_dev:v0.0.1-1
    # image: liyaodev/tmpagent_dev:v0.0.1-1
    build:
      context: .
      dockerfile: build/docker/cpu.Dockerfile
      # dockerfile: build/docker/gpu.Dockerfile
    ports:
      - 8080:8080
    environment:
      ENV_CONFIG: ${ENV_CONFIG}
    volumes:
      - .:/www/server
      - ${TMPAGENT_DIR:-.}/volumes/vscode-extensions:/www/.vscode-server
    
    postgres:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_USER=${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
        POSTGRES_DB=demo
      ports:
        - ${postgres_PORT:-5432}:5432
      volumes:
        - ${TMPAGENT_DIR:-.}/volumes/postgres:/var/lib/postgresql/data/
    
    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: False
      ports:
        - ${PGADMIN_PORT:-5050}:80
      volumes:
        - ${TMPAGENT_DIR:-.}/volumes/pgadmin:/var/lib/pgadmin
      restart: unless-stopped


networks:
  default:
    name: tmpagent_dev
